import Head from 'next/head';

import Navbar from '@/sections/Navbar';
import Hero from '@/sections/Hero';
import About from '@/sections/About';
import Features from '@/sections/Features';
import Demo from '@/sections/Demo';
import FAQ from '@/sections/FAQ';
import Contact from '@/sections/Contact';
import Footer from '@/sections/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`bg-dark min-h-screen w-full px-8 relative scroll-smooth`}>
        <Navbar />
        <Hero />
        <About />
        <Features />
        <Demo/>
        <FAQ />
        <Contact />
        <Footer/>
      </main>
    </>
  );
}
